language: java
jdk:
  - openjdk14
script: ./gradlew shadowJar
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  email: false
